// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Go Fiber Boilerplate API",
        "description": "A production-ready REST API boilerplate built with Fiber, GORM, and PostgreSQL",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "1.0.0"
    },
    "host": "localhost:4000",
    "basePath": "/",
    "paths": {
        "/health": {
            "get": {
                "description": "Check API health status",
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "operationId": "health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/books": {
            "get": {
                "description": "Get all books with optional search and pagination",
                "tags": [
                    "Books"
                ],
                "summary": "Get all books",
                "operationId": "getBooks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Book"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            },
            "post": {
                "description": "Create a new book",
                "tags": [
                    "Books"
                ],
                "summary": "Create a book",
                "operationId": "createBook",
                "parameters": [
                    {
                        "description": "Book object",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Book"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Book"
                        }
                    },
                    "400": {
                        "description": "Invalid request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/books/{id}": {
            "get": {
                "description": "Get a book by ID",
                "tags": [
                    "Books"
                ],
                "summary": "Get a book",
                "operationId": "getBook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Book"
                        }
                    },
                    "404": {
                        "description": "Book not found"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            },
            "put": {
                "description": "Update a book",
                "tags": [
                    "Books"
                ],
                "summary": "Update a book",
                "operationId": "updateBook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Book object",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Book"
                        }
                    },
                    "400": {
                        "description": "Invalid request"
                    },
                    "404": {
                        "description": "Book not found"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            },
            "delete": {
                "description": "Delete a book",
                "tags": [
                    "Books"
                ],
                "summary": "Delete a book",
                "operationId": "deleteBook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Book not found"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/books/search": {
            "get": {
                "description": "Search books by title, author, or ISBN",
                "tags": [
                    "Books"
                ],
                "summary": "Search books",
                "operationId": "searchBooks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword (title, author, or ISBN)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Book"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing search query"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Book": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "Author name",
                    "type": "string",
                    "example": "John Doe"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "description": {
                    "description": "Book description",
                    "type": "string",
                    "example": "A great book about Go programming"
                },
                "id": {
                    "description": "Book ID",
                    "type": "integer",
                    "example": 1
                },
                "isbn": {
                    "description": "ISBN (unique)",
                    "type": "string",
                    "example": "978-3-16-148410-0"
                },
                "pages": {
                    "description": "Number of pages",
                    "type": "integer",
                    "example": 300
                },
                "publisher": {
                    "description": "Publisher name",
                    "type": "string",
                    "example": "Tech Books Inc"
                },
                "title": {
                    "description": "Book title",
                    "type": "string",
                    "example": "The Go Programming Language"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "year": {
                    "description": "Publication year",
                    "type": "integer",
                    "example": 2015
                }
            }
        },
        "models.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Book deleted successfully"
                }
            }
        }
    }
}
`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

func init() {
	swag.Register(swag.Name, &swaggerInfo{
		Version:     "1.0.0",
		Host:        "localhost:4000",
		BasePath:    "/",
		Schemes:     []string{},
		Title:       "Go Fiber Boilerplate API",
		Description: "A production-ready REST API boilerplate built with Fiber, GORM, and PostgreSQL",
	})
}
